baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = 'graysx'
title = 'Folsom Lake Accounting'

## Site Settings
[params]
logo = "assets/img/logo.webp"
favicon = "assets/favicon.png"

# Info
address = "Folsom, CA"
email = "karen@folsomlakeaccounting.com"
phone = "888-345-7533"

# Socials
linkedin = "https://www.linkedin.com/in/karen-haase-lee/"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Services"
  URL = "#services"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#contact"
  weight = 3


# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04